# Generated by Django 3.0 on 2020-09-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20200914_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpending',
            name='trackingnumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
